# Generated by Django 6.0.1 on 2026-02-01 15:09

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_aadhaar_card_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='google_auth',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='patient_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
