# Generated by Django 6.0.1 on 2026-02-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('appointment', 'Appointment'), ('alert', 'System Alert'), ('report', 'Medical Report'), ('profile', 'Profile Update')], default='alert', max_length=20),
        ),
    ]
