# Generated by Django 6.0.1 on 2026-02-01 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_doctor_available_days_doctor_available_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='meeting_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='available_days',
            field=models.CharField(default='Mon-Fri', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='available_time',
            field=models.CharField(default='09:00 AM - 05:00 PM', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.department'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(default='General Physician', help_text='e.g. Heart Surgeon', max_length=100),
        ),
    ]
