# Generated by Django 6.0.1 on 2026-02-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_appointment_meeting_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Auto-generated video link', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='available_days',
            field=models.CharField(default='Mon-Fri', help_text='e.g. Mon-Fri', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='available_time',
            field=models.CharField(default='09:00 AM - 05:00 PM', help_text='e.g. 09:00 AM - 05:00 PM', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(default='General Physician', help_text='e.g. Heart Surgeon, Pediatrician', max_length=100),
        ),
    ]
