# Generated by Django 6.0.1 on 2026-02-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_alter_appointment_id_alter_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('doctor_missed', 'Doctor Missed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, help_text='Years of experience (Used for ranking)'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('General Physician', 'General Physician'), ('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Orthopedic', 'Orthopedic'), ('Neurologist', 'Neurologist'), ('Pediatrician', 'Pediatrician'), ('Psychiatrist', 'Psychiatrist'), ('Dentist', 'Dentist'), ('ENT', 'ENT Specialist')], default='General Physician', help_text='Specialization for recommendation engine', max_length=100),
        ),
    ]
