# Generated by Django 6.0.1 on 2026-02-05 05:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_alter_appointment_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_doctors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('General Physician', 'General Physician'), ('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Orthopedic', 'Orthopedic'), ('Neurologist', 'Neurologist'), ('Pediatrician', 'Pediatrician'), ('Psychiatrist', 'Psychiatrist'), ('Dentist', 'Dentist'), ('ENT', 'ENT Specialist'), ('Gynecologist', 'Gynecologist')], default='General Physician', help_text='Specialization for recommendation engine', max_length=100),
        ),
    ]
