# Generated by Django 6.0.1 on 2026-02-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_doctor_favorited_by_alter_doctor_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('General Physician', 'General Physician'), ('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Orthopedic', 'Orthopedic'), ('Neurologist', 'Neurologist'), ('Pediatrician', 'Pediatrician'), ('Psychiatrist', 'Psychiatrist'), ('Dentist', 'Dentist'), ('ENT', 'ENT Specialist'), ('Gynecologist', 'Gynecologist')], default='General Physician', help_text='Select specialization. The Department will automatically update to match this.', max_length=100),
        ),
    ]
