# Generated by Django 6.0.1 on 2026-03-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_alter_department_name_alter_doctor_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reschedule_count',
            field=models.IntegerField(default=0),
        ),
    ]
