# Generated by Django 6.0.1 on 2026-01-31 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_options_appointment_completed_at_and_more'),
        ('records', '0002_medicalreport_delete_medicalrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalreport',
            name='description',
        ),
        migrations.RemoveField(
            model_name='medicalreport',
            name='file',
        ),
        migrations.RemoveField(
            model_name='medicalreport',
            name='title',
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='attachment',
            field=models.FileField(blank=True, help_text='Upload Lab PDF or X-Ray', null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='diagnosis',
            field=models.CharField(default='Pending Diagnosis', help_text='Main condition', max_length=255),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='doctor_notes',
            field=models.TextField(blank=True, help_text='Additional advice', null=True),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='lab_tests',
            field=models.TextField(blank=True, help_text='Required tests (optional)', null=True),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='medications',
            field=models.TextField(default='No medications prescribed', help_text='Prescribed medicines'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='symptoms',
            field=models.TextField(default='No symptoms recorded', help_text='Patient symptoms'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_report', to='appointments.appointment'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authored_reports', to='appointments.doctor'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
