# Generated by Django 6.0.1 on 2026-03-06 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_alter_medicalreport_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('insight_type', models.CharField(choices=[('daily', 'Daily Summary'), ('weekly', 'Weekly Trend'), ('clinical', 'Clinical Report Analysis')], default='daily', max_length=20)),
                ('summary_text', models.TextField(help_text='The non-medical synthesis generated by the AI')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitalsync_insights', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedLabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report_file', models.FileField(upload_to='vitalsync_reports/')),
                ('extracted_data', models.JSONField(blank=True, default=dict, help_text='Structured data extracted via OCR')),
                ('abnormalities', models.TextField(blank=True, help_text='Flags generated by the AI for out-of-range values')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitalsync_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('mood', models.CharField(blank=True, max_length=50)),
                ('stress_level', models.IntegerField(blank=True, help_text='Scale of 1-10', null=True)),
                ('diet_summary', models.TextField(blank=True)),
                ('symptoms', models.TextField(blank=True)),
                ('chat_log', models.JSONField(blank=True, default=dict, help_text='Stores the Gemini chat history')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitalsync_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('patient', 'date')},
            },
        ),
    ]
