# Generated by Django 6.0.1 on 2026-03-06 05:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_healthinsight_uploadedlabreport_dailycheckin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailycheckin',
            name='chat_log',
        ),
        migrations.RemoveField(
            model_name='dailycheckin',
            name='diet_summary',
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='chat_history',
            field=models.JSONField(blank=True, default=list, help_text='Stores the Agentic AI conversation history'),
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dailycheckin',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dailycheckin',
            name='sleep_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthinsight',
            name='insight_type',
            field=models.CharField(choices=[('daily', 'Daily Lifestyle Summary'), ('weekly', 'Weekly Health Trend'), ('clinical', 'Clinical Report Synthesis')], default='daily', max_length=20),
        ),
        migrations.AlterField(
            model_name='healthinsight',
            name='summary_text',
            field=models.TextField(help_text='Professional synthesis generated by Dual-AI Architecture'),
        ),
        migrations.AlterField(
            model_name='uploadedlabreport',
            name='abnormalities',
            field=models.TextField(blank=True, help_text='AI-flagged out-of-range clinical values'),
        ),
        migrations.AlterField(
            model_name='uploadedlabreport',
            name='extracted_data',
            field=models.JSONField(blank=True, default=dict, help_text='Parameters extracted from lab report'),
        ),
        migrations.AlterField(
            model_name='uploadedlabreport',
            name='report_file',
            field=models.FileField(help_text='Secure upload for AI analysis', upload_to='vitalsync_reports/'),
        ),
    ]
